fix: Merge the same translation words #108
casbin/casdoor pull request #111
Opened 2021-06-15 21:49 UTC by turbodog03

## merged 'code's into one section, and added some translation support. Add package-lock.json to .gitignore.

### added(fixed) translations：
![image](https://user-images.githubusercontent.com/63595854/122126971-14becf00-ce65-11eb-8efd-e4294e59e659.png)
![image](https://user-images.githubusercontent.com/63595854/122127077-3ddf5f80-ce65-11eb-84f2-61e109d83ba4.png)
![image](https://user-images.githubusercontent.com/63595854/122127167-5cddf180-ce65-11eb-8b6a-ad7c715a68fd.png)

### code changes:
* I found some blocks like "token:Application", but there're no "token" section in en.json or zh.json files. so I edited them to be like "general:Application", and add their translation into the two .json files.
* I merged all statements in the two .json files that include "code" into one section named "code".

2021-06-16 02:52 UTC, hsluoyz commented
@Kininaru plz review.

2021-06-16 05:42 UTC, Kininaru reviewed
Please do not add `package-lock.json`. Other changes look fine.

2021-06-16 06:52 UTC, hsluoyz commented
@turbodog03 remove Merge commits:

![image](https://user-images.githubusercontent.com/3787410/122171641-896c2a80-ceb2-11eb-9f2f-bdb692623ee3.png)

2021-06-17 14:05 UTC, Kininaru reviewed
Please remove `web/package-lock.json`. Other changes look fine.

2021-06-17 15:10 UTC, hsluoyz requested changes
Don't change anything if you don't know how it works

2021-06-17 15:10 UTC, hsluoyz commented on web/.gitignore
> +package-lock.json
Don't change this

2021-06-17 15:10 UTC, hsluoyz commented on .gitignore
> +
Don't change this

2021-06-17 15:10 UTC, hsluoyz commented on web/src/auth/SignupPage.js
> -    const required = signupItem.required;
Don't change these

2021-06-17 15:27 UTC, closed without merging