feat: show users for each organization
casbin/casdoor pull request #120
Opened 2021-06-18 16:03 UTC by sh1luo

Fix: #119 
Signed-off-by: wasabi <690898835@qq.com>

2021-06-18 16:04 UTC, sh1luo commented
demo link: http://test.rescld.cn

admin,123

2021-06-18 17:10 UTC, hsluoyz requested changes

2021-06-18 17:10 UTC, hsluoyz commented on web/src/OrganizationUserListPage.js
> +// Copyright 2021 The casbin Authors. All Rights Reserved.
Like I said, plz re-use the React component for https://door.casbin.com/users

2021-06-19 03:37 UTC, closed without merging

2021-06-19 14:07 UTC, hsluoyz commented
Replaced by: https://github.com/casbin/casdoor/pull/121