feat: Send-code-button-should-be-gray-out-with-empty-or-invalid-Email…
casbin/casdoor pull request #129
Opened 2021-06-23 03:43 UTC by sh1luo

…-or-phone

Fix: #110 
Signed-off-by: wasabi <690898835@qq.com>

2021-06-23 03:45 UTC, sh1luo commented
demo link: http://testb.rescld.cn/signup

Have to be aware of is that the regular expression of email comes from the source code of antd(<https://github.com/yiminghe/async-validator/blob/057b0b047f88fac65457bae691d6cb7c6fe48ce1/src/rule/type.ts#L9>)

the regular expression of email comes from [here](https://regexr.com/3c53v)

2021-06-23 12:59 UTC, hsluoyz requested changes

2021-06-23 12:59 UTC, hsluoyz commented on web/src/auth/SignupPage.js
> +                  if( (/^\s*$|^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/).test(this.state.
Put it to Setting.js, provide reference in comment

2021-06-23 12:59 UTC, hsluoyz commented on web/src/auth/SignupPage.js
> +                  if ( (/^\s*$|^[+]*[(]?[0-9]{1,4}[)]?[-\s/0-9]*$/).test(this.state.phone)) {
Put it to Setting.js, provide reference in comment

2021-06-24 11:57 UTC, hsluoyz requested changes

2021-06-24 11:57 UTC, hsluoyz commented on web/src/auth/SignupPage.js
> +import {EmailRegEx, PhoneRegEx} from "../Setting.js"
see: `import * as Setting from "../Setting";`

2021-06-24 14:05 UTC, hsluoyz approved these changes

2021-06-24 14:05 UTC, merged

2021-08-11 15:09 UTC, hsluoyz commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/casbin/casdoor/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: