fix: Move proxy address config to app.conf
casbin/casdoor pull request #138
Opened 2021-07-02 03:28 UTC by WindSpiritSR

Deployed at: https://door.leviatan.cn

You can signup from https://forum.leviatan.cn, then try to link github account and signin with github provider, this pr will work if these are successful

Signed-off-by: WindSpiritSR <simon343riley@gmail.com>

2021-07-04 07:03 UTC, hsluoyz requested changes

2021-07-04 07:03 UTC, hsluoyz commented on controllers/util.go
> +	if len(httpProxy) == 0 {
httpProxy == ""

2021-07-04 07:03 UTC, hsluoyz commented on conf/app.conf
>  useProxy = false
Then `useProxy` can be removed.

2021-07-04 07:15 UTC, WindSpiritSR commented
fixed

2021-07-04 08:00 UTC, hsluoyz approved these changes

2021-07-04 08:00 UTC, merged

2021-08-11 15:09 UTC, hsluoyz commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/casbin/casdoor/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: