feat: add linkedin provider
casbin/casdoor pull request #144
Opened 2021-07-03 12:55 UTC by sh1luo

Signed-off-by: wasabi <690898835@qq.com>

2021-07-03 12:55 UTC, sh1luo commented
demo link: http://1.13.13.178/

2021-07-03 14:16 UTC, hsluoyz requested changes
Another question is that can it get the profile URL for a LinkedIn user? 


Another bug: http://1.13.13.178/account , login admin, 123 , you will get:

![image](https://user-images.githubusercontent.com/3787410/124357103-52d13680-dc4c-11eb-8ccd-b93f6833686b.png)

2021-07-03 14:16 UTC, hsluoyz commented on web/src/ProviderEditPage.js
> +          {id: 'Linkedin', name: 'Linkedin'},
All places should change to "LinkedIn", "I" is upper-case.

2021-07-04 04:11 UTC, sh1luo commented
@hsluoyz I fix the bug at `http://1.13.13.178/account `, now which won't report error in console. And I changed all `Linkedin` to `LinkedIn`

But I did not find the user profile url, because the suffix of the user profile url is customized and can be modified at will. I have not yet found the api to obtain this value.

For example, my profile url is: `https://www.linkedin.com/in/jikunliu/`

2021-07-04 08:26 UTC, hsluoyz requested changes

2021-07-04 08:26 UTC, hsluoyz commented on web/src/auth/Provider.js
> +  } else if (provider.type === "Linkedin") {
I or i? Did you test the code?

2021-07-04 08:35 UTC, sh1luo commented
@hsluoyz I'm sorry it was my mistake, now it's ok.

2021-07-04 14:12 UTC, hsluoyz commented
@sh1luo plz attach the demo link for each PR.

2021-07-04 14:12 UTC, hsluoyz approved these changes

2021-07-06 04:03 UTC, sh1luo commented
> demo link: http://1.13.13.178/

@hsluoyz

2021-07-09 09:07 UTC, merged