feat: support login UI customization
casbin/casdoor pull request #146
Opened 2021-07-04 09:21 UTC by 1340908470

2021-07-05 17:11 UTC, hsluoyz commented
@1340908470 demo

2021-07-05 17:11 UTC, hsluoyz commented
@Kininaru @sh1luo plz review.

2021-07-06 11:30 UTC, sh1luo requested changes

2021-07-06 11:30 UTC, sh1luo commented on web/src/auth/LoginPageCustom.js
> +        if (document.getElementById("login") && document.getElementById("username") &&
Do not show debugging info.

2021-07-06 11:30 UTC, sh1luo commented on web/src/auth/LoginPage.js
> +          return <LoginPageCustom Parent={this} Application={this.state.classes.application } Html={this.state.classes.application.loginPageCustom}/>
`if (this.state.application?.loginPageCustom  !== "")`, other than `app&&app.loginPageCustom`

2021-07-06 11:30 UTC, sh1luo commented on yarn.lock
> +
Does not seem to need this lock file

2021-07-07 03:30 UTC, Kininaru reviewed
Please do not use DOM APIs. Use React state instead.

2021-07-07 03:30 UTC, Kininaru commented on web/src/auth/LoginPageCustom.js
> +import React from 'react'
Casbin License

2021-07-07 04:50 UTC, Kininaru approved these changes

2021-07-07 07:01 UTC, hsluoyz commented
@1340908470 plz remember to provide demo link for each PR.

2021-07-08 17:14 UTC, 1340908470 commented
[Demo Link](http://chenweihao.vip/)

### test html string:
```html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>登录</title>
    <link rel="stylesheet" href="../css/login.css" />
    <link rel="stylesheet" href="https://cdn.staticfile.org/font-awesome/4.7.0/css/font-awesome.css">
    <style>
        body {
            background: url('../image/2.jpg');
            background-repeat: no-repeat;
            background-size: 100% auto;
        }

        #login-box {
            width: 70%;
            height: auto;
            margin: 0 auto;
            margin-top: 13%;
            text-align: center;
            background: #00000060;
            padding: 20px 50px;
        }

        #login-box h1 {
            color: #fff;
        }

        #login-box .form .item {
            margin-top: 15px;
        }

        #login-box .form .item i {
            font-size: 18px;
            color: #fff;
        }

        #login-box .form .item input {
            width: 180px;
            font-size: 18px;
            border: 0;
            border-bottom: 2px solid #fff;
            padding: 5px 10px;
            background: #ffffff00;
            color: #fff;
        }

        #login-box button {
            margin-top: 20px;
            width: 190px;
            height: 30px;
            font-size: 20px;
            font-weight: 700;
            color: #fff;
            background-image: linear-gradient(to right, #74ebd5 0%, #9face6 100%);
            border: 0;
            border-radius: 15px;
        }
    </style>
</head>

<body>
    <div id="login-box">
        <h1>Login</h1>
        <div class="form">
            <div class="item"> <i class="fa fa-github-alt" style="font-size:24px"></i> <input id="username" type="text"
                    placeholder="Username"></div>
            <div class="item">
                <i class="fa fa-search" style="font-size:24px"></i> <input id="password" type="password"
                    placeholder="Password">
            </div>
            <input id="remember" name="checkbox" type="checkbox" value="checkbox" checked="checked" />
            Auto login
        </div> <button id="login">Login</button>
        <br/>
        <a id="forget">forgot password</a>
        <br/>
        <a id="signup">sign up now</a>
    </div>
</body>

</html>
```

2021-07-10 13:05 UTC, hsluoyz commented
@1340908470 plz resolve:

![image](https://user-images.githubusercontent.com/3787410/125164016-8f5bdf80-e1c2-11eb-8879-f1c51fa58696.png)

2021-07-19 13:58 UTC, hsluoyz commented
@1340908470 plz fix the wrong commits.

2021-07-25 01:49 UTC, closed without merging