feat: add run casdoor through docker
casbin/casdoor pull request #162
Opened 2021-07-13 03:14 UTC by oranges-eating

Signed-off-by: killer <1533063601@qq.com>

2021-07-13 03:18 UTC, oranges-eating commented
@hsluoyz If there is no problem in this part, I will do the docker installation of casnode.

2021-07-13 08:50 UTC, hsluoyz commented
@Kininaru @ErikQQY plz review.

2021-07-13 13:31 UTC, ErikQQY approved these changes
I tested locally, everything works fine for me.

![Screenshot from 2021-07-13 21-26-36](https://user-images.githubusercontent.com/52615090/125460326-c448266b-1788-47a9-b1d1-3c70c206ed09.png)

2021-07-13 13:58 UTC, sh1luo requested changes

2021-07-13 13:58 UTC, sh1luo commented on go-dockerfile
> +ENV PATH=$PATH:/casdoor/node-v12.22.0-linux-x64/bin
I think if there are multiple commands should be displayed in separate lines to increase readability, like this:
```shell
RUN commandA &&
         commandB &&
         commandC &&
         and etc...
```

2021-07-13 13:58 UTC, sh1luo commented on go-dockerfile
> +CMD ./wait-for-it db:3306 && ./main
Same as above.

2021-07-13 14:29 UTC, oranges-eating commented
@hsluoyz Is there still any problem? If there is no problem, I will write casnode's dockerfile

2021-07-14 06:28 UTC, oranges-eating commented
@hsluoyz Is have any question?

2021-07-14 06:37 UTC, hsluoyz requested changes

2021-07-14 06:37 UTC, hsluoyz commented on README.md
> +## RUN through Docker
Run

2021-07-14 06:37 UTC, hsluoyz commented on README.md
> +- Vi casdoor/conf/app.conf
vi ?

2021-07-14 06:37 UTC, hsluoyz commented on README.md
> +  http://your-ip:8000/
Does localhost work?

2021-07-14 06:37 UTC, hsluoyz commented on docker-compose.yml
> +
No so many new lines

2021-07-14 06:48 UTC, oranges-eating commented
@hsluoyz already solved

2021-07-14 09:24 UTC, hsluoyz approved these changes

2021-07-14 09:24 UTC, merged

2021-07-14 09:25 UTC, hsluoyz commented
@oranges-eating put the docs to: https://casdoor.org/