feat: add basic layout frame
casbin/casdoor pull request #172
Opened 2021-07-15 13:45 UTC by turbodog03

# I add a basic layout frame for casdoor. Includes collapsible sidebar, header, context and footer.

## changes:
* I moved the navigation menu from header to sidebar ( so we can show other electments on header and homepage.
* Move the muti-language select box from footer to header and use a select for selections. #165
* Add icons for each menu items.
* Add breadcrumb( to be improved
* Add siteName and logoPath to conf.js, to enable users to customerize it
* Online demo: http://39.106.18.82/
## to be improved
* Develop a dynamic breadcrumb
* Make a new homepage, to show backend datas.
* Optimize the components
* Add more features if needed

2021-07-15 13:48 UTC, turbodog03 commented
please review @nodece

2021-07-15 14:04 UTC, nodece commented on web/src/basic/HomePage.js
> +    // ];
Remove commented code.

2021-07-15 14:06 UTC, nodece commented on web/src/basic/HomePage.js
> +        {/* <span className= "contentTitle">
Remove the commented out code.

2021-07-15 14:07 UTC, nodece commented on web/src/basic/SingleCard.js
> +      // <Card.Grid style={gridStyle} onClick={() => Setting.goToLinkSoft(this, link)}>
Remove the commented out code.

2021-07-15 14:07 UTC, nodece commented on web/src/basic/SingleCard.js
> +        {/* <img src={logo} alt="logo" height={60} style={{marginBottom: '20px'}}/> */}
Remove the commented out code.

2021-07-15 14:10 UTC, nodece commented on web/src/component/SelectLanguageBox.js
> +  // render() {
Remove the commented out code.

2021-07-15 14:13 UTC, nodece commented on web/src/component/SelectLanguageBox.js
> +  onClick = function (e) {
So it looks cleaner:
```
onClick(e) {
// todo
}
```

2021-07-15 14:28 UTC, nodece requested changes

2021-07-15 14:28 UTC, nodece commented on web/src/layout/index.js
> +// 引入子菜单组件
Remove this comment.

2021-07-15 14:28 UTC, nodece commented on web/src/layout/index.js
> +    console.log(collapsed);
Remove `console`.

2021-07-15 14:28 UTC, nodece commented on web/src/layout/index.js
> +    console.log(this.props.path);
Remove `console`

2021-07-15 15:12 UTC, nodece approved these changes
LGTM

2021-07-16 06:39 UTC, hsluoyz commented
@turbodog03 I don't think this layout is anything better than our existing look.

1. I don't like the sidebar. It takes more space of the width.
2. The UI look is neither fancy or professional. It is actually very similar to the Casbin-dashabord project which has failed one year ago (https://github.com/casbin/casbin-dashboard) . 

I can't name a strong reason to accept this huge PR as a whole. Maybe some minor improvements are welcome, like language select, path conf, etc.

![image](https://user-images.githubusercontent.com/3787410/125902825-a7fe7356-07d6-478a-972a-29452a1a4154.png)

2021-07-16 12:55 UTC, closed without merging