feat: fix header bugs, improve UI, optimize touchscreen experience
casbin/casdoor pull request #187
Opened 2021-07-22 15:11 UTC by turbodog03

# changes:
* Fix header overflow 
![image](https://user-images.githubusercontent.com/63595854/126661592-2c9675bf-f559-4fad-9dd0-5236b912a197.png)
* Fix account dropdown disappear 
![image](https://user-images.githubusercontent.com/63595854/126661705-0a696f7d-cc39-420c-ae24-18c1b701e8de.png)
* Add background color and card to warp content
* Add scroll for tables
* Optimize tables for touchscreen, the table won't overflow anymore
![image](https://user-images.githubusercontent.com/63595854/126662394-284cfca0-ffc3-4420-89f2-ef4966a30164.png)
![image](https://user-images.githubusercontent.com/63595854/126662443-b3c47ce0-84e0-44b0-85ef-929a817138df.png)
* Improve the dropdown UI when hover

# Preview:
http://39.106.18.82/

2021-07-22 15:16 UTC, turbodog03 commented
Please review @nodece

2021-07-22 15:51 UTC, hsluoyz requested changes

2021-07-22 15:51 UTC, hsluoyz commented on web/src/App.js
> +        <Route exact path="/result" render={(props) => this.renderHomeIfLoggedIn(<ResultPage {...props} />)}/>
Why repeat the routes?

2021-07-22 15:51 UTC, hsluoyz commented on web/src/UserListPage.js
> +import { Content } from "antd/lib/layout/layout";
I don't think we should import "antd/lib/layout/layout"

2021-07-22 16:33 UTC, hsluoyz requested changes

2021-07-22 16:33 UTC, hsluoyz commented on web/src/LdapTable.js
> +import { Content } from "antd/lib/layout/layout";
Content is not used?

2021-07-22 16:33 UTC, hsluoyz commented on web/src/App.js
> +              {this.renderRouter()}
{
xxx
}

2021-07-22 16:33 UTC, hsluoyz commented on web/src/App.js
> +      {this.renderRouter()}
{
xxx
}

2021-07-22 16:34 UTC, hsluoyz commented
@Kininaru @sh1luo plz review.

2021-07-22 17:29 UTC, Kininaru approved these changes
Mobile UI still looks strange, and some display bugs: 

![image](https://user-images.githubusercontent.com/42638489/126682775-e2bfc6cb-78b6-4491-a0af-05ba32adde58.png)

Maybe we can fix these bugs in future?

2021-07-23 01:45 UTC, hsluoyz commented
@Kininaru OK, let's fix the mobile view in next PR.

2021-07-23 01:45 UTC, hsluoyz approved these changes

2021-07-23 01:46 UTC, merged