feat: support local storage
casbin/casdoor pull request #224
Opened 2021-08-05 03:48 UTC by sh1luo

Signed-off-by: sh1luo <690898835@qq.com>

2021-08-05 03:49 UTC, sh1luo commented
Demo link: http://testb.rescld.cn/

2021-08-06 12:29 UTC, hsluoyz commented
@Kininaru @WindSpiritSR plz review

2021-08-07 06:32 UTC, WindSpiritSR requested changes

2021-08-07 06:32 UTC, WindSpiritSR commented on object/storage.go
>  	//"github.com/qor/oss/qiniu"
Remove useless packages

2021-08-07 09:11 UTC, Kininaru requested changes
The function works well, and maybe we should:

1. Add a explanation in README or in doc site to tell users to add `client_max_body_size 20m;` in Nginx http statement, to upload large pictures.
2. It looks like that path strings have some problems. Maybe we can fix that later.

2021-08-07 09:11 UTC, Kininaru commented on object/storage.go
> -	//"github.com/qor/oss/qiniu"
Please set your Goland -> Editor -> Code Style -> Go like this: 
![image](https://user-images.githubusercontent.com/42638489/128595259-d7089d4e-c62b-4f43-9c80-c2d75373a2d4.png)

2021-08-07 09:28 UTC, sh1luo commented
@Kininaru ok, fixed.

2021-08-07 09:42 UTC, Kininaru approved these changes

2021-08-07 13:34 UTC, WindSpiritSR approved these changes

2021-08-08 03:39 UTC, hsluoyz commented
@sh1luo plz refactor the PR and implement the `oss.StorageInterface` interface for local file system: https://github.com/casbin/casdoor/commit/22d021d17319c98b7fde053aadceedc135accdaf

2021-08-08 04:52 UTC, sh1luo commented
@hsluoyz ok, done, demo link: http://testb.rescld.cn/

2021-08-08 06:18 UTC, merged