feat: support default provider
casbin/casdoor pull request #226
Opened 2021-08-05 09:16 UTC by WindSpiritSR

fixed: #222 

Signed-off-by: WindSpiritSR <simon343riley@gmail.com>

2021-08-05 11:55 UTC, hsluoyz commented
@WindSpiritSR demo link

2021-08-05 11:56 UTC, hsluoyz commented
@Kininaru @sh1luo

2021-08-05 11:59 UTC, WindSpiritSR commented
Deployed at: https://door.leviatan.cn

2021-08-06 03:23 UTC, sh1luo requested changes

2021-08-06 03:23 UTC, sh1luo commented on web/src/ProviderTable.js
>      let columns = [
A little bloated. Replaced by:
```javascript
if (table.some(item => item.default)) {
    defaultProvider = item.name;
    return false;
}
```

2021-08-06 03:23 UTC, sh1luo commented on web/src/ProviderTable.js
>              }} />
I think that it's no need to update `defaultProvider`, which is set by application admin and can be empty.

Only need to decide whether to set `default=true` according to ``canSignUp || canSignIn``

Writing in this way will cause the logic of the partial code to be complicated and difficult to maintain.

2021-08-06 03:23 UTC, sh1luo commented on web/src/auth/LoginPage.js
> +    })
same as above

2021-08-06 03:25 UTC, sh1luo commented
@WindSpiritSR Forgot to say, except for codes. This demo looks very good.

2021-08-06 03:32 UTC, hsluoyz requested changes

2021-08-06 03:32 UTC, hsluoyz commented on web/src/ApplicationEditPage.js
> +      defaultProvider: null,
@WindSpiritSR yes, as @sh1luo suggested, remove this `defaultProvider` state.

2021-08-06 03:32 UTC, hsluoyz commented on web/src/ApplicationEditPage.js
> +                <LoginPage type={"login"} mode={"signup"} application={this.state.application} preview="true" />
Change to `isPreview`

2021-08-06 12:27 UTC, hsluoyz requested changes

2021-08-06 12:27 UTC, hsluoyz commented on web/src/ApplicationEditPage.js
> +
No this

2021-08-06 12:27 UTC, hsluoyz commented on web/src/ApplicationEditPage.js
> +              enablePassword={this.state.application.enablePassword}
Don't pass in enablePassword

2021-08-06 12:27 UTC, hsluoyz commented on web/src/ApplicationEditPage.js
> +            <LoginPage type={"login"} mode={"signin"} application={this.state.application} isPreview="true" />
I don't think `isPreview` is useful, use this.props.application

2021-08-06 14:04 UTC, closed without merging