fix: improve code specification
casbin/casdoor pull request #231
Opened 2021-08-06 16:13 UTC by sh1luo

Signed-off-by: sh1luo <690898835@qq.com>

2021-08-06 16:13 UTC, sh1luo commented
In this pr, I mainly did four things:

1. add comment for exported function, which the first letter is capital.
2. Remove unnecessary code, such as `break`, `else`, Inappropriate usage of strings package and double quotes escape problem, etc. 

Finally, get `A` score in [Go Report](https://goreportcard.com/).

3. Re-write README, making the directory structure clearer and optimize the content. Now directory structure like this:
![image](https://user-images.githubusercontent.com/51157931/128537687-692e5afb-1b3f-4877-b64b-28a67b27dd39.png)

4. add good badges, which makes casdoor README looks better, online demo: [DEMO](https://github.com/sh1luo/casdoor/tree/fix-improve-code-specification)

2021-08-06 16:18 UTC, hsluoyz commented
@kocoler @Kininaru @WindSpiritSR plz review

2021-08-07 13:43 UTC, WindSpiritSR requested changes

2021-08-07 13:43 UTC, WindSpiritSR commented on README.md
> +cd web/ && npm run start
`go mod tidy` & `npm install` ~

2021-08-07 13:43 UTC, WindSpiritSR commented on README.md
> +cd web/ && npm run build
same as above ~

2021-08-07 13:54 UTC, sh1luo commented
@WindSpiritSR ok, fixed.

2021-08-07 14:02 UTC, hsluoyz commented
lgtm

2021-08-07 14:02 UTC, merged

2021-08-11 15:08 UTC, hsluoyz commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/casbin/casdoor/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: