fix: support saml http post binding
casbin/casdoor pull request #2661
Opened 2024-01-31 19:16 UTC by dacongda

Fix: #2643 

support saml http post binding when sp use post method

![3407f30a1d0fe7eb885472b57577606c](https://github.com/casbin/casdoor/assets/47297289/9dae4ac2-eab7-42b9-a278-dbd8aef4dd1e)

2024-02-01 06:36 UTC, hsluoyz requested changes

2024-02-01 06:36 UTC, hsluoyz commented on web/src/ApplicationEditPage.js
> +            {Setting.getLabel(i18next.t("application:Enable SAML Post Binding"), i18next.t("application:Enable SAML Post Binding - Tooltip"))} :
Enable SAML POST binding

2024-02-01 06:36 UTC, hsluoyz commented on controllers/saml.go
> +		enablePostBinding = "true"
Why default is true? As we agreed, it's false by default

2024-02-01 06:36 UTC, hsluoyz commented on controllers/saml.go
> +	samlResponse := c.Input().Get("SAMLRequest")
Is this `SAMLRequest` spelling correct?

2024-02-01 06:36 UTC, hsluoyz commented on controllers/saml.go
> +	if enablePostBinding == "" {
Define `enablePostBinding` as boolean

2024-02-01 06:36 UTC, hsluoyz commented on controllers/saml.go
> +	c.Redirect(targetURL, 303)
Don't use int value 303

2024-02-01 06:36 UTC, hsluoyz commented on object/saml_idp.go
> +	originF, _ := getOriginFromHost(host)
Handle error

2024-02-01 06:36 UTC, hsluoyz commented on web/src/ApplicationEditPage.js
> +    ApplicationBackend.getSamlMetadata("admin", this.state.applicationName, checked ?? false)
Just use `checked`

2024-02-01 06:36 UTC, hsluoyz commented on web/src/backend/ApplicationBackend.js
> +  return fetch(`${Setting.ServerUrl}/api/saml/metadata?application=${owner}/${encodeURIComponent(name)}&post=${enablePostBinding}`, {
`&enablePostBinding=${xxx}`

2024-02-01 06:36 UTC, hsluoyz commented on web/src/locales/es/data.json
> +    "Enable SAML Post Binding": "Habilitar el enlace SAML POST",
No need to translate langs other than zh

2024-02-01 09:28 UTC, merged

2024-08-28 07:13 UTC, tiny-v commented
hi, 

i'm using Azure as the SP， Casdoor as the IDP,  and i already enable the Saml Post Binding, but still get the "Unexpected EOF" error when login.

2024-08-28 07:15 UTC, tiny-v commented
![image](https://github.com/user-attachments/assets/6e00fe9d-a4b8-4bd9-9371-5cf23d7ebe0e)

2024-08-28 09:58 UTC, hsluoyz commented
@tiny-v create issue and show it's a bug (not your own issue, we don't fix your own issue). Don't comment on old post