feat: support third-party application to login with SAML rather than only Casdoor itself
casbin/casdoor pull request #350
Opened 2021-12-08 14:30 UTC by seriouszyx

Signed-off-by: Yixiang Zhao <seriouszyx@foxmail.com>

2021-12-08 17:49 UTC, hsluoyz commented
@Steve0x2a plz review

2021-12-09 11:34 UTC, Steve0x2a approved these changes
lgtm!

2021-12-09 15:13 UTC, hsluoyz requested changes

2021-12-09 15:13 UTC, hsluoyz commented on controllers/auth.go
> +		slice[4], relayState, samlResponse)
define `slice[4]` in a var, don't use it directly

2021-12-09 16:23 UTC, merged