feat: add Keycloak idp support
casbin/casdoor pull request #356
Opened 2021-12-11 05:29 UTC by seriouszyx

Signed-off-by: Yixiang Zhao <seriouszyx@foxmail.com>

2021-12-11 05:54 UTC, hsluoyz commented
@Steve0x2a plz review

2021-12-11 06:18 UTC, hsluoyz commented
@seriouszyx demo link?

2021-12-11 10:17 UTC, seriouszyx commented
@hsluoyz 
- Casdoor demo link: http://82.156.216.21:8000/login 
  - Aliyun
    - username: admin
    - password: Admin123456!
  - Keycloak
    - username: admin
    - password: 123
- Keycloak demo link: http://82.156.216.21:8080/auth  Administrator console
  - username: admin
  - password: 123
  - realm: Master
  - clients name: `http://82.156.216.21:8000/api/acs `

2021-12-11 15:31 UTC, hsluoyz commented
@seriouszyx the demo looks great! Just a minor issue in profile UI: http://82.156.216.21:8000/account

![image](https://user-images.githubusercontent.com/3787410/145682148-ed190c61-2e4a-4be9-a0b1-915582ac3296.png)

2021-12-13 05:03 UTC, Steve0x2a requested changes
lgtm

2021-12-13 05:03 UTC, Steve0x2a commented on object/saml.go
> +	return str[tagLength : len(str) - tagLength - 1]
`return res[1]` can get the same result and avoid using slices.

2021-12-13 11:39 UTC, seriouszyx commented
@hsluoyz Fixed.

![image](https://user-images.githubusercontent.com/33992371/145805635-543336c4-aea1-45f1-89e6-641faca1c6d1.png)

2021-12-13 11:49 UTC, hsluoyz commented
lgtm

2021-12-13 11:49 UTC, merged