feat: add WeChatIdProvider
casbin/casdoor pull request #62
Opened 2021-05-16 03:27 UTC by 1340908470

The interface is not consistent to Tencent official struct, so I added a new interface
**Related documents:** [微信接口调用说明](https://developers.weixin.qq.com/doc/oplatform/Website_App/WeChat_Login/Authorized_Interface_Calling_UnionID.html)

2021-05-16 15:48 UTC, hsluoyz requested changes

2021-05-16 16:44 UTC, 1340908470 commented on idp/weChat.go
> +	// - ClientID: 应用唯一标识, 用于请求CODE、通过CODE获取/刷新access_token，此信息前端可获取
Related content has been deleted

2021-05-17 06:16 UTC, hsluoyz approved these changes

2021-05-17 06:17 UTC, merged

2021-08-11 15:10 UTC, hsluoyz commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/casbin/casdoor/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: