feat: add "forget password" [front & backend]
casbin/casdoor pull request #72
Opened 2021-05-25 15:11 UTC by 1340908470

feat: add "forget password" [front & backend]

2021-05-25 15:51 UTC, hsluoyz commented
@Kininaru plz review.

2021-05-27 13:34 UTC, Kininaru requested changes

2021-05-27 13:34 UTC, Kininaru commented on controllers/user.go
> +		object.DisableVerificationCode(form.Phone)
We should not disable the verification code until the reset action is successfully completed.

2021-05-27 13:34 UTC, Kininaru commented on web/src/auth/ForgetPage.js
> +              placeHolder={"Verify code"}
Use i18next here.

2021-05-27 13:34 UTC, Kininaru commented on web/src/auth/ForgetPage.js
> +              placeHolder={"Verify code"}
Use i18next here.

2021-05-27 13:34 UTC, Kininaru commented on web/src/auth/SelfForgetPage.js
> +        account={this.props.account}
It seems like that `account` is not used in `ForgetPage`. And it is impossible to have an account here when I forgot my password.

2021-05-27 13:34 UTC, Kininaru commented on web/src/auth/ForgetPage.js
> +      Util.showMessage("error", `Unknown forgot type: ${this.state.type}`);
i18next here

2021-05-27 13:34 UTC, Kininaru commented on web/src/auth/ForgetPage.js
> +              message: "Please input your application!",
i18next here

2021-05-27 13:34 UTC, Kininaru commented on web/src/auth/ForgetPage.js
> +              message: "Please input your organization!",
i18next here

2021-05-27 13:34 UTC, Kininaru commented on web/src/auth/ForgetPage.js
> +              message: "Please input your Email/Phone string!",
i18next here

2021-05-27 13:34 UTC, Kininaru commented on web/src/component/CountDownInput.js
> +        );
These lines repeated for 3 times, but only 1 line of them are different. I suggest we can write these lines in a more elegant way.

2021-05-27 15:33 UTC, Kininaru requested changes

2021-05-27 15:33 UTC, Kininaru commented on web/src/auth/ForgetPage.js
> +      Util.showMessage("error", `Unknown forgot type: ${this.state.type}`);
Maybe we can write like this: 
```javascripts
Util.showMessage("error", i18next.t(`forget:Unknown forgot type: `) + this.state.type);
```

2021-05-27 15:45 UTC, Kininaru requested changes

2021-05-27 15:45 UTC, Kininaru commented on web/src/auth/ForgetPage.js
> +      Util.showMessage("error", i18next.t(`forget:Unknown forgot type: `) + this.state.type);
Then here should be: 
```javascripts
Util.showMessage("error", i18next.t("forgetPassword:Unknown forgot type:" + this.state.type);
```

I haven't noticed that there is a key `forgetPassword` in i18n, sorry...

2021-05-27 15:54 UTC, Kininaru approved these changes
LGTM

2021-05-28 02:13 UTC, hsluoyz commented
@1340908470 plz provide demo link.

2021-05-29 11:23 UTC, hsluoyz commented
@1340908470 squash all commits into one

2021-05-29 11:33 UTC, 1340908470 commented
> @1340908470 squash all commits into one

done

2021-05-31 09:13 UTC, Kininaru commented
Backend did not check if the email or phone belong to the user.

2021-05-31 12:10 UTC, hsluoyz requested changes

2021-05-31 12:10 UTC, hsluoyz commented on controllers/user.go
> +	"github.com/casdoor/casdoor/util"
sort

2021-05-31 12:10 UTC, hsluoyz commented on web/src/auth/AuthBackend.js
> +      `${authConfig.serverUrl}/api/login${oAuthParamsToQuery(oAuthParams)}`,
Don't ajust the format anywhere in this PR

2021-05-31 12:10 UTC, hsluoyz commented on object/init.go
> +		HomepageUrl:    "https://casdoor.org",
Why do you commit something that is already there?

https://github.com/casbin/casdoor/blob/0f8a46fe0bd286caa0aed7658dff22c8a67e5927/object/init.go#L53-L73

2021-06-01 13:07 UTC, closed without merging