feat: add dingtalk provider
casbin/casdoor pull request #94
Opened 2021-06-08 13:51 UTC by sh1luo

Signed-off-by: zKen <690898835@qq.com>

2021-06-08 13:58 UTC, sh1luo commented
demo url:

http://test.leviatan.cn/login/oauth/authorize?client_id=f1e350a2de4846dac700&response_type=code&redirect_uri=https://kcode.icu&scope=read&state=casdoor

click dingtalk logo:
account: 15236176076
password: test1234

this is admin account,you can see the configuration information:
account: admin
password: 123

2021-06-08 16:25 UTC, hsluoyz requested changes

2021-06-08 16:25 UTC, hsluoyz commented on idp/dingtalk.go
> +		return nil, errors.New(fmt.Sprintf("登录错误：%d, %s", errCode, info.Errmsg))
Use English at all places

2021-06-08 16:25 UTC, hsluoyz commented on idp/dingtalk.go
> +	timestamp := strconv.FormatInt(time.Now().UnixNano()/1e6, 10) // 毫秒时间戳
Use English at all places

2021-06-09 03:14 UTC, hsluoyz approved these changes

2021-06-09 03:15 UTC, merged